services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend.dev
    image: genai-nodejs-course-nestjs-backend:dev
    container_name: genai-nodejs-course-nestjs-backend
    restart: unless-stopped

    ports:
      - '5000:5000'

    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:5432/devdb
      REDIS_URL: redis://host.docker.internal:6379
      MONGO_URL: mongodb://root:root@host.docker.internal:27017
      QDRANT_URL: http://host.docker.internal:6333

    command: npm run start:dev

    extra_hosts:
      - 'host.docker.internal:host-gateway'

    develop:
      watch:
        # Sync backend source
        - action: sync
          path: ../
          target: /app
          ignore:
            - node_modules/
            - dist/

        # Rebuild if dependencies change
        - action: rebuild
          path: ../package.json
