FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

# Install Nest CLI globally (optional)
RUN npm install -g @nestjs/cli

COPY . .

EXPOSE 5000

CMD ["npm", "run", "start:dev"]



#########################
# Production Dockerfile (for reference, not used in compose.yaml)
#########################
# ===============================
# Build Stage
# ===============================
# FROM node:22-alpine AS builder

# WORKDIR /app

# COPY package*.json ./
# RUN npm ci

# COPY . .
# RUN npm run build

# ===============================
# Production Stage
# ===============================
# FROM node:22-alpine

# WORKDIR /app

# Create non-root user
# RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# COPY package*.json ./
# RUN npm ci --omit=dev

# COPY --from=builder /app/dist ./dist

# Switch to non-root user

# USER appuser

# EXPOSE 5000

# CMD ["node", "dist/main.js"]
